# This workflow builds the pushes to the master branch and bumps the version.

name: Builder
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'setup.py'
      - '.bumpversion.cfg'
      - 'samples/'
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.MLSKELETION_GITHUB_BOT_TOKEN }}
      if: github.repository == 'sathiyakugan/mlskeleton'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade bump2version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test packaging
      run: |
        # stop the build if there are tests that fail
        python tests/test_generator.py
    - name: Bump version
      run: |
        git config --local user.email "version.bump@github.action.com"
        git config --local user.name "mlskeleton-github-bot"
        bumpversion patch
        git push --follow-tags
      if: github.repository == 'sathiyakugan/mlskeleton'